sudo: required
services:
   - docker



before_install:
   - docker build -t nitin/docker-react -f Dockerfile.dev .


script:
   - docker run -e CI=true nitin/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-1"
   app: "docker-react"
   env: "DockerReact-env"
   bucket-name: "elasticbeanstalk-us-east-1-189921624580"
   bucket_path: "docker-react"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
     secure: "$AWS_SECRET_KEY"      


